replicaCount: 1
environment: staging

image:
  repository: uadeel421/reliance-shippingservice
  pullPolicy: Always
  tag: "latest"

service:
  port: 50051

nodeSelector:
  pool: stagingpool

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
