apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend-destination-rule
  namespace: hipster-app
spec:
  host: frontend.hipster-app.svc.cluster.local
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
  # trafficPolicy:
  # loadBalancer:
  #   simple: RANDOM
