//
// Autogenerated by Thrift Compiler (0.16.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');


var ttypes = require('./demo_types');
//HELPER FUNCTIONS AND STRUCTURES

var EmailService_SendOrderConfirmation_args = function(args) {
  this.email = null;
  this.order = null;
  if (args) {
    if (args.email !== undefined && args.email !== null) {
      this.email = args.email;
    }
    if (args.order !== undefined && args.order !== null) {
      this.order = new ttypes.OrderResult(args.order);
    }
  }
};
EmailService_SendOrderConfirmation_args.prototype = {};
EmailService_SendOrderConfirmation_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.email = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.order = new ttypes.OrderResult();
        this.order.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

EmailService_SendOrderConfirmation_args.prototype.write = function(output) {
  output.writeStructBegin('EmailService_SendOrderConfirmation_args');
  if (this.email !== null && this.email !== undefined) {
    output.writeFieldBegin('email', Thrift.Type.STRING, 1);
    output.writeString(this.email);
    output.writeFieldEnd();
  }
  if (this.order !== null && this.order !== undefined) {
    output.writeFieldBegin('order', Thrift.Type.STRUCT, 2);
    this.order.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var EmailService_SendOrderConfirmation_result = function(args) {
};
EmailService_SendOrderConfirmation_result.prototype = {};
EmailService_SendOrderConfirmation_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

EmailService_SendOrderConfirmation_result.prototype.write = function(output) {
  output.writeStructBegin('EmailService_SendOrderConfirmation_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var EmailServiceClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
EmailServiceClient.prototype = {};
EmailServiceClient.prototype.seqid = function() { return this._seqid; };
EmailServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };

EmailServiceClient.prototype.SendOrderConfirmation = function(email, order, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_SendOrderConfirmation(email, order);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_SendOrderConfirmation(email, order);
  }
};

EmailServiceClient.prototype.send_SendOrderConfirmation = function(email, order) {
  var output = new this.pClass(this.output);
  var params = {
    email: email,
    order: order
  };
  var args = new EmailService_SendOrderConfirmation_args(params);
  try {
    output.writeMessageBegin('SendOrderConfirmation', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

EmailServiceClient.prototype.recv_SendOrderConfirmation = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new EmailService_SendOrderConfirmation_result();
  result.read(input);
  input.readMessageEnd();

  callback(null);
};
var EmailServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
EmailServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
};
EmailServiceProcessor.prototype.process_SendOrderConfirmation = function(seqid, input, output) {
  var args = new EmailService_SendOrderConfirmation_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.SendOrderConfirmation.length === 2) {
    Q.fcall(this._handler.SendOrderConfirmation.bind(this._handler),
      args.email,
      args.order
    ).then(function(result) {
      var result_obj = new EmailService_SendOrderConfirmation_result({success: result});
      output.writeMessageBegin("SendOrderConfirmation", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("SendOrderConfirmation", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.SendOrderConfirmation(args.email, args.order, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new EmailService_SendOrderConfirmation_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("SendOrderConfirmation", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("SendOrderConfirmation", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
