//
// Autogenerated by Thrift Compiler (0.16.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');


var ttypes = require('./demo_types');
//HELPER FUNCTIONS AND STRUCTURES

var RecommendationService_ListRecommendations_args = function(args) {
  this.selected_ids = null;
  if (args) {
    if (args.selected_ids !== undefined && args.selected_ids !== null) {
      this.selected_ids = Thrift.copyList(args.selected_ids, [null]);
    }
  }
};
RecommendationService_ListRecommendations_args.prototype = {};
RecommendationService_ListRecommendations_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.LIST) {
        this.selected_ids = [];
        var _rtmp316 = input.readListBegin();
        var _size15 = _rtmp316.size || 0;
        for (var _i17 = 0; _i17 < _size15; ++_i17) {
          var elem18 = null;
          elem18 = input.readString();
          this.selected_ids.push(elem18);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RecommendationService_ListRecommendations_args.prototype.write = function(output) {
  output.writeStructBegin('RecommendationService_ListRecommendations_args');
  if (this.selected_ids !== null && this.selected_ids !== undefined) {
    output.writeFieldBegin('selected_ids', Thrift.Type.LIST, 1);
    output.writeListBegin(Thrift.Type.STRING, this.selected_ids.length);
    for (var iter19 in this.selected_ids) {
      if (this.selected_ids.hasOwnProperty(iter19)) {
        iter19 = this.selected_ids[iter19];
        output.writeString(iter19);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var RecommendationService_ListRecommendations_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [null]);
    }
  }
};
RecommendationService_ListRecommendations_result.prototype = {};
RecommendationService_ListRecommendations_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        this.success = [];
        var _rtmp321 = input.readListBegin();
        var _size20 = _rtmp321.size || 0;
        for (var _i22 = 0; _i22 < _size20; ++_i22) {
          var elem23 = null;
          elem23 = input.readString();
          this.success.push(elem23);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RecommendationService_ListRecommendations_result.prototype.write = function(output) {
  output.writeStructBegin('RecommendationService_ListRecommendations_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRING, this.success.length);
    for (var iter24 in this.success) {
      if (this.success.hasOwnProperty(iter24)) {
        iter24 = this.success[iter24];
        output.writeString(iter24);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var RecommendationServiceClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
RecommendationServiceClient.prototype = {};
RecommendationServiceClient.prototype.seqid = function() { return this._seqid; };
RecommendationServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };

RecommendationServiceClient.prototype.ListRecommendations = function(selected_ids, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_ListRecommendations(selected_ids);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_ListRecommendations(selected_ids);
  }
};

RecommendationServiceClient.prototype.send_ListRecommendations = function(selected_ids) {
  var output = new this.pClass(this.output);
  var params = {
    selected_ids: selected_ids
  };
  var args = new RecommendationService_ListRecommendations_args(params);
  try {
    output.writeMessageBegin('ListRecommendations', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

RecommendationServiceClient.prototype.recv_ListRecommendations = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new RecommendationService_ListRecommendations_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('ListRecommendations failed: unknown result');
};
var RecommendationServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
RecommendationServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
};
RecommendationServiceProcessor.prototype.process_ListRecommendations = function(seqid, input, output) {
  var args = new RecommendationService_ListRecommendations_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.ListRecommendations.length === 1) {
    Q.fcall(this._handler.ListRecommendations.bind(this._handler),
      args.selected_ids
    ).then(function(result) {
      var result_obj = new RecommendationService_ListRecommendations_result({success: result});
      output.writeMessageBegin("ListRecommendations", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("ListRecommendations", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.ListRecommendations(args.selected_ids, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new RecommendationService_ListRecommendations_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("ListRecommendations", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("ListRecommendations", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
