allowedCopyrightHolders:
  - 'PitiRR'

allowedLicenses:
  - 'Apache-2.0'

# If you want to ignore certain files/folders, use ignoreFiles.
ignoreFiles:
 - '*'

# If you want to ignore checking the license year, use ignoreLicenseYear.
# ignoreLicenseYear: true # Useful when migrating in code licensed at previous years.

# sourceFileExtensions:
#   - 'cs'
#   - 'css'
#   - 'Dockerfile'
#   - 'dockerignore'
#   - 'gitignore'
#   - 'go'
#   - 'html'
#   - 'java'
#   - 'js'
#   - 'proto'
#   - 'py'
#   - 'sh'
#   - 'tf'
#   - 'yaml'
#   - 'yml'
