{
 "title": "Boutique App DashBoard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "chaosresult_name",
    "label": "Chaos Result",
    "query": {
     "query": "label_values(litmuschaos_awaited_experiments{job=~\"chaos-exporter\"}, chaosresult_name)"
    }
   },
   {
    "name": "chaosengine_context",
    "label": "Chaos Engine context",
    "query": {
     "query": "label_values(litmuschaos_experiment_verdict{job=~\"chaos-exporter\"}, chaosengine_context)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Probe Success Percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=\"frontend.boutique.svc.cluster.local:80\", job=\"prometheus-blackbox-exporter\"}[60s:1s])*100"
    }
   ]
  },
  {
   "title": "Frontend QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(otelcol_exporter_sent_spans[1m]) * 60",
     "legendFormat": "QPS"
    },
    {
     "expr": "rate(otelcol_exporter_sent_spans[1m]) * 60",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Access Duration (Frontend service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{job=\"prometheus-blackbox-exporter\", instance=\"frontend.boutique.svc.cluster.local:80\"}[60s:1s])*1000"
    }
   ]
  },
  {
   "title": "Cart QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(otelcol_exporter_sent_spans[1m]) * 60",
     "legendFormat": "QPS"
    },
    {
     "expr": "rate(otelcol_exporter_sent_spans[1m]) * 60",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Access Duration(cartservice)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{job=\"prometheus-blackbox-exporter\", instance=\"cartservice.boutique.svc.cluster.local:7070\"}[60s:1s])*1000"
    }
   ]
  },
  {
   "title": "Product QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(otelcol_exporter_sent_spans[1m]) * 60",
     "legendFormat": "QPS"
    },
    {
     "expr": "rate(otelcol_exporter_sent_spans[1m]) * 60",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Access Duration(ProductCatalogservice)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{job=\"prometheus-blackbox-exporter\", instance=\"productcatalogservice.boutique.svc.cluster.local:3550\"}[60s:1s])*1000"
    }
   ]
  },
  {
   "title": "Checkout Qps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(otelcol_exporter_sent_spans[1m]) * 60",
     "legendFormat": "QPS"
    },
    {
     "expr": "rate(otelcol_exporter_sent_spans[1m]) * 60",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Access Duration(checkoutservice)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{job=\"prometheus-blackbox-exporter\", instance=\"checkoutservice.boutique.svc.cluster.local:5050\"}[60s:1s])*1000"
    }
   ]
  },
  {
   "title": "Currency Service Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{job=\"prometheus-blackbox-exporter\", instance=\"currencyservice.boutique.svc.cluster.local:7000\"}[60s:1s])*1000"
    }
   ]
  },
  {
   "title": "Access Duration(Adservice)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{job=\"prometheus-blackbox-exporter\", instance=\"adservice.boutique.svc.cluster.local:9555\"}[60s:1s])*1000"
    }
   ]
  },
  {
   "title": "Access Duration(redis-cart)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds{job=\"prometheus-blackbox-exporter\", instance=\"redis-cart.boutique.svc.cluster.local:6379\"}[60s:1s])*1000"
    }
   ]
  }
 ]
}