app:
  name: "online-boutique"
  description: "This is a sample configuration for MyApp."
  version: "1.0.0"
  maintainers:
    - name: "John Doe"
      email: "johndoe@example.com"
  repository: "https://github.com/gumb0t/microservices-demo"
