apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-deployment
  namespace: staging
  labels:
    app: paymentservice
    environment: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
      environment: staging
  template:
    metadata:
      labels:
        app: paymentservice
        environment: staging
    spec:
      nodeSelector:
        kubernetes.azure.com/agentpool: stgpool
      containers:
        - name: paymentservice
          image: uadeel421/reliance-paymentservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          envFrom:
            - configMapRef:
                name: paymentservice-config
          livenessProbe:
            exec:
              command: ["/usr/bin/grpc_health_probe", "-addr=:50051"]
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            exec:
              command: ["/usr/bin/grpc_health_probe", "-addr=:50051"]
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
