replicaCount: 1
environment: staging

image:
  repository: uadeel421/reliance-productcatalogservice
  pullPolicy: Always
  tag: "latest"

service:
  port: 3550

nodeSelector:
  workload-type: staging-pool

# This secret will be created from the values below
secrets:
  SSL_CERT_PATH: "/ssl/DigiCertGlobalRootCA.crt.pem"

# This references the existing secret for the SSL cert file
sslVolume:
  secretName: ssl-certificates

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

secretProvider:
  keyvaultName: "kpskeyvault"
  tenantId: "1c127d2d-2d00-477a-b479-3104cb849681"
  userAssignedIdentityID: "0f25cea3-7f60-40b8-98d7-a87116e002dc"    
