replicaCount: 1
environment: staging

image:
  repository: uadeel421/reliance-productcatalogservice
  pullPolicy: Always
  tag: "latest"

service:
  port: 3550

nodeSelector:
  pool: stgpool

# This secret will be created from the values below
secrets:
  MYSQL_USER: "kpadmin"
  MYSQL_PASSWORD: "p1Kistan0978^"
  MYSQL_HOST: "liverwdbserver.mysql.database.azure.com"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "hipstershop"
  SSL_CERT_PATH: "/ssl/DigiCertGlobalRootCA.crt.pem"

# This references the existing secret for the SSL cert file
sslVolume:
  secretName: productcatalog-ssl-certs

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
