apiVersion: apps/v1
kind: secretproviderclass
metadata:
  name: azure-keyvault-secrets
  namespace: staging  # Ensure this matches your namespace
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "e45729fe-4814-4037-9b53-ae33be273c1a"  # Replace with your actual identity ID
    keyvaultName: "your-keyvault-name"  # Replace with your actual Key Vault name
    objects: |
      array:
        - |
          objectName: Database-URL
          objectType: secret
        - |
          objectName: SECRET-KEY
          objectType: secret
        - |
          objectName: SSL-CERT
          objectType: secret
    tenantId: "your-tenant-id"  # Replace with your actual tenant ID