---
AWSTemplateFormatVersion: 2010-09-09
Description: mirzaganteng - with ProductCatalog and EmailService

Parameters:
  ClusterName:
    Type: String
    Default: my-eks-cluster
    Description: Name of the EKS cluster

  LabRoleArn:
    Type: String
    Default: arn:aws:iam::992382648201:role/LabRole
    Description: ARN of the existing LabRole (check your AWS Academy console for exact ARN)

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${ClusterName}-VPC

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${ClusterName}-IGW

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Public Subnets
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${ClusterName}-PublicSubnet1
        - Key: kubernetes.io/role/elb
          Value: 1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${ClusterName}-PublicSubnet2
        - Key: kubernetes.io/role/elb
          Value: 1

  # Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ClusterName}-PublicRT

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  SubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  # Security Group for EKS Cluster
  ClusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EKS cluster
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ClusterName}-SG

  # EKS Cluster (using LabRole)
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      Version: "1.32"
      RoleArn: !Ref LabRoleArn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref ClusterSecurityGroup
        SubnetIds:
          - !Ref PublicSubnet1
          - !Ref PublicSubnet2
        EndpointPublicAccess: true
        EndpointPrivateAccess: false

  # EKS Node Group (using LabRole)
  NodeGroup:
    Type: AWS::EKS::Nodegroup
    DependsOn: EKSCluster
    Properties:
      ClusterName: !Ref ClusterName
      NodegroupName: !Sub ${ClusterName}-nodegroup
      NodeRole: !Ref LabRoleArn
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      ScalingConfig:
        MinSize: 1
        DesiredSize: 2
        MaxSize: 3
      InstanceTypes:
        - t2.micro
      AmiType: AL2_x86_64

  # -------------------------------------------------------------------------
  # Product Catalog Service Resources (ADDED)
  # -------------------------------------------------------------------------
  ProductCatalogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "product-catalog-${AWS::AccountId}"

  ProductCatalogFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ProductCatalogService
      Handler: index.lambda_handler
      Role: !Ref LabRoleArn
      Runtime: python3.9
      Timeout: 10
      Environment:
        Variables:
          BUCKET_NAME: !Ref ProductCatalogBucket
          FILE_KEY: products.json
      Code:
        ZipFile: |
          import json
          import boto3
          import os

          s3 = boto3.client('s3')

          def lambda_handler(event, context):
              bucket_name = os.environ.get('BUCKET_NAME')
              file_key = os.environ.get('FILE_KEY', 'products.json')
              
              if not bucket_name:
                  return {'statusCode': 500, 'body': json.dumps({'error': 'BUCKET_NAME not set'})}

              try:
                  response = s3.get_object(Bucket=bucket_name, Key=file_key)
                  file_content = response['Body'].read().decode('utf-8')
                  products_data = json.loads(file_content)
                  
                  if 'id' in event:
                      product_id = event['id']
                      for product in products_data.get('products', []):
                          if product['id'] == product_id:
                              return {
                                  'statusCode': 200, 
                                  'headers': {'Content-Type': 'application/json'},
                                  'body': json.dumps(product)
                              }
                      return {'statusCode': 404, 'body': json.dumps({'error': 'Product not found'})}
                      
                  return {
                      'statusCode': 200, 
                      'headers': {'Content-Type': 'application/json'},
                      'body': json.dumps(products_data)
                  }

              except Exception as e:
                  return {'statusCode': 500, 'body': json.dumps({'error': str(e)})}

  # -------------------------------------------------------------------------
  # Email Service Resources (ADDED)
  # -------------------------------------------------------------------------
  OrderNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: OrderNotification
      DisplayName: Order Confirmation

  EmailServiceFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: EmailService
      Handler: index.lambda_handler
      Role: !Ref LabRoleArn
      Runtime: python3.9
      Timeout: 10
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref OrderNotificationTopic
      Code:
        ZipFile: |
          import json
          import boto3
          import os

          sns = boto3.client('sns')

          def lambda_handler(event, context):
              sns_topic_arn = os.environ.get('SNS_TOPIC_ARN')
              
              if not sns_topic_arn:
                  return {'statusCode': 500, 'body': json.dumps({'error': 'SNS_TOPIC_ARN not set'})}

              if 'body' in event:
                  try:
                      body = json.loads(event['body'])
                  except:
                      body = event
              else:
                  body = event

              order_id = body.get('order', {}).get('order_id', 'N/A')
              message = f"Halo! Pesanan #{order_id} sudah diterima. Terima kasih!"

              try:
                  sns.publish(
                      TopicArn=sns_topic_arn,
                      Subject=f"Konfirmasi Pesanan #{order_id}",
                      Message=message
                  )
                  return {'statusCode': 200, 'body': json.dumps({'message': 'Notifikasi terkirim!'})}

              except Exception as e:
                  return {'statusCode': 500, 'body': json.dumps({'error': str(e)})}

Outputs:
  ClusterName:
    Description: EKS Cluster Name
    Value: !Ref EKSCluster
    Export:
      Name: !Sub ${AWS::StackName}-ClusterName

  ClusterEndpoint:
    Description: EKS Cluster Endpoint
    Value: !GetAtt EKSCluster.Endpoint
    Export:
      Name: !Sub ${AWS::StackName}-ClusterEndpoint

  ClusterArn:
    Description: EKS Cluster ARN
    Value: !GetAtt EKSCluster.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ClusterArn

  VPCId:
    Description: VPC ID
    Value: !Ref VPC

  SubnetIds:
    Description: Subnet IDs
    Value: !Sub ${PublicSubnet1},${PublicSubnet2}

  ProductCatalogBucketName:
    Description: Name of the S3 bucket for products
    Value: !Ref ProductCatalogBucket
  
  ProductCatalogFunctionName:
    Description: Name of the Product Catalog Lambda function
    Value: !Ref ProductCatalogFunction
  
  EmailServiceFunctionName:
    Description: Name of the Email Service Lambda function
    Value: !Ref EmailServiceFunction
  
  SNSTopicArn:
    Description: ARN of the SNS Topic
    Value: !Ref OrderNotificationTopic
