pipeline:
  name: productcatalogservice
  identifier: productcatalogservice
  tags: {}
  template:
    templateRef: Golang_CI_pipeline
    versionLabel: "1"
    gitBranch: main
    templateInputs:
      stages:
        - stage:
            identifier: Build
            template:
              templateInputs:
                type: CI
                variables:
                  - name: module_path
                    type: String
                    value: <+input>
      properties:
        ci:
          codebase:
            build: <+input>
  projectIdentifier: Ovi_sandbox
  orgIdentifier: DOPS_Labs
