pipeline:
  name: productcatalogservice
  identifier: productcatalogservice
  tags: {}
  template:
    templateRef: Golang_CI_pipeline
    versionLabel: "1"
    gitBranch: main
    templateInputs:
      properties:
        ci:
          codebase:
            build: <+input>
  projectIdentifier: Ovi_sandbox
  orgIdentifier: DOPS_Labs
