apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: aegis-backend
    newName: aegis-backend
    newTag: dev
  - name: aegis-dashboard
    newName: aegis-dashboard
    newTag: dev

patches:
  - target:
      kind: ConfigMap
      name: aegis-config
    patch: |-
      - op: replace
        path: /data/AEGIS_RUNTIME_MODE
        value: dev
      - op: replace
        path: /data/AEGIS_ALLOWED_ORIGINS
        value: http://aegis.local
  - target:
      kind: Ingress
      name: aegis-dashboard
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: aegis.local
