apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: staging
  labels:
    app: checkoutservice
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
    environment: staging
  ports:
    - name: grpc
      protocol: TCP
      port: 5050
      targetPort: 5050