// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: shoppinghistoryservice.proto

package hipstershop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Positions     []*HistoryOrderItem    `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_shoppinghistoryservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoppinghistoryservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_shoppinghistoryservice_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetPositions() []*HistoryOrderItem {
	if x != nil {
		return x.Positions
	}
	return nil
}

type HistoryOrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryOrderItem) Reset() {
	*x = HistoryOrderItem{}
	mi := &file_shoppinghistoryservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryOrderItem) ProtoMessage() {}

func (x *HistoryOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_shoppinghistoryservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryOrderItem.ProtoReflect.Descriptor instead.
func (*HistoryOrderItem) Descriptor() ([]byte, []int) {
	return file_shoppinghistoryservice_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryOrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *HistoryOrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_shoppinghistoryservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoppinghistoryservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_shoppinghistoryservice_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrdersOfUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersOfUserRequest) Reset() {
	*x = GetOrdersOfUserRequest{}
	mi := &file_shoppinghistoryservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersOfUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersOfUserRequest) ProtoMessage() {}

func (x *GetOrdersOfUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoppinghistoryservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersOfUserRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersOfUserRequest) Descriptor() ([]byte, []int) {
	return file_shoppinghistoryservice_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrdersOfUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderRequest) Reset() {
	*x = DeleteOrderRequest{}
	mi := &file_shoppinghistoryservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderRequest) ProtoMessage() {}

func (x *DeleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shoppinghistoryservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_shoppinghistoryservice_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type HistoryOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	OrderItems    []*HistoryOrderItem    `protobuf:"bytes,4,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryOrder) Reset() {
	*x = HistoryOrder{}
	mi := &file_shoppinghistoryservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryOrder) ProtoMessage() {}

func (x *HistoryOrder) ProtoReflect() protoreflect.Message {
	mi := &file_shoppinghistoryservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryOrder.ProtoReflect.Descriptor instead.
func (*HistoryOrder) Descriptor() ([]byte, []int) {
	return file_shoppinghistoryservice_proto_rawDescGZIP(), []int{5}
}

func (x *HistoryOrder) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *HistoryOrder) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HistoryOrder) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *HistoryOrder) GetOrderItems() []*HistoryOrderItem {
	if x != nil {
		return x.OrderItems
	}
	return nil
}

type HistoryOrders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*HistoryOrder        `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryOrders) Reset() {
	*x = HistoryOrders{}
	mi := &file_shoppinghistoryservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryOrders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryOrders) ProtoMessage() {}

func (x *HistoryOrders) ProtoReflect() protoreflect.Message {
	mi := &file_shoppinghistoryservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryOrders.ProtoReflect.Descriptor instead.
func (*HistoryOrders) Descriptor() ([]byte, []int) {
	return file_shoppinghistoryservice_proto_rawDescGZIP(), []int{6}
}

func (x *HistoryOrders) GetOrders() []*HistoryOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_shoppinghistoryservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shoppinghistoryservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_shoppinghistoryservice_proto_rawDescGZIP(), []int{7}
}

var File_shoppinghistoryservice_proto protoreflect.FileDescriptor

const file_shoppinghistoryservice_proto_rawDesc = "" +
	"\n" +
	"\x1cshoppinghistoryservice.proto\x12\x16shoppinghistoryservice\x1a\x1fgoogle/protobuf/timestamp.proto\"u\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12F\n" +
	"\tpositions\x18\x02 \x03(\v2(.shoppinghistoryservice.HistoryOrderItemR\tpositions\"M\n" +
	"\x10HistoryOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"1\n" +
	"\x16GetOrdersOfUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"/\n" +
	"\x12DeleteOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\xc8\x01\n" +
	"\fHistoryOrder\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12I\n" +
	"\vorder_items\x18\x04 \x03(\v2(.shoppinghistoryservice.HistoryOrderItemR\n" +
	"orderItems\"M\n" +
	"\rHistoryOrders\x12<\n" +
	"\x06orders\x18\x01 \x03(\v2$.shoppinghistoryservice.HistoryOrderR\x06orders\"\x0f\n" +
	"\rEmptyResponse2\xa0\x03\n" +
	"\x16ShoppingHistoryService\x12_\n" +
	"\vCreateOrder\x12*.shoppinghistoryservice.CreateOrderRequest\x1a$.shoppinghistoryservice.HistoryOrder\x12Y\n" +
	"\bGetOrder\x12'.shoppinghistoryservice.GetOrderRequest\x1a$.shoppinghistoryservice.HistoryOrder\x12h\n" +
	"\x0fGetOrdersOfUser\x12..shoppinghistoryservice.GetOrdersOfUserRequest\x1a%.shoppinghistoryservice.HistoryOrders\x12`\n" +
	"\vDeleteOrder\x12*.shoppinghistoryservice.DeleteOrderRequest\x1a%.shoppinghistoryservice.EmptyResponseB\\ZZgithub.com/GoogleCloudPlatform/microservices-demo/src/checkoutservice/genproto;hipstershopb\x06proto3"

var (
	file_shoppinghistoryservice_proto_rawDescOnce sync.Once
	file_shoppinghistoryservice_proto_rawDescData []byte
)

func file_shoppinghistoryservice_proto_rawDescGZIP() []byte {
	file_shoppinghistoryservice_proto_rawDescOnce.Do(func() {
		file_shoppinghistoryservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shoppinghistoryservice_proto_rawDesc), len(file_shoppinghistoryservice_proto_rawDesc)))
	})
	return file_shoppinghistoryservice_proto_rawDescData
}

var file_shoppinghistoryservice_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_shoppinghistoryservice_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),     // 0: shoppinghistoryservice.CreateOrderRequest
	(*HistoryOrderItem)(nil),       // 1: shoppinghistoryservice.HistoryOrderItem
	(*GetOrderRequest)(nil),        // 2: shoppinghistoryservice.GetOrderRequest
	(*GetOrdersOfUserRequest)(nil), // 3: shoppinghistoryservice.GetOrdersOfUserRequest
	(*DeleteOrderRequest)(nil),     // 4: shoppinghistoryservice.DeleteOrderRequest
	(*HistoryOrder)(nil),           // 5: shoppinghistoryservice.HistoryOrder
	(*HistoryOrders)(nil),          // 6: shoppinghistoryservice.HistoryOrders
	(*EmptyResponse)(nil),          // 7: shoppinghistoryservice.EmptyResponse
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
}
var file_shoppinghistoryservice_proto_depIdxs = []int32{
	1, // 0: shoppinghistoryservice.CreateOrderRequest.positions:type_name -> shoppinghistoryservice.HistoryOrderItem
	8, // 1: shoppinghistoryservice.HistoryOrder.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: shoppinghistoryservice.HistoryOrder.order_items:type_name -> shoppinghistoryservice.HistoryOrderItem
	5, // 3: shoppinghistoryservice.HistoryOrders.orders:type_name -> shoppinghistoryservice.HistoryOrder
	0, // 4: shoppinghistoryservice.ShoppingHistoryService.CreateOrder:input_type -> shoppinghistoryservice.CreateOrderRequest
	2, // 5: shoppinghistoryservice.ShoppingHistoryService.GetOrder:input_type -> shoppinghistoryservice.GetOrderRequest
	3, // 6: shoppinghistoryservice.ShoppingHistoryService.GetOrdersOfUser:input_type -> shoppinghistoryservice.GetOrdersOfUserRequest
	4, // 7: shoppinghistoryservice.ShoppingHistoryService.DeleteOrder:input_type -> shoppinghistoryservice.DeleteOrderRequest
	5, // 8: shoppinghistoryservice.ShoppingHistoryService.CreateOrder:output_type -> shoppinghistoryservice.HistoryOrder
	5, // 9: shoppinghistoryservice.ShoppingHistoryService.GetOrder:output_type -> shoppinghistoryservice.HistoryOrder
	6, // 10: shoppinghistoryservice.ShoppingHistoryService.GetOrdersOfUser:output_type -> shoppinghistoryservice.HistoryOrders
	7, // 11: shoppinghistoryservice.ShoppingHistoryService.DeleteOrder:output_type -> shoppinghistoryservice.EmptyResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_shoppinghistoryservice_proto_init() }
func file_shoppinghistoryservice_proto_init() {
	if File_shoppinghistoryservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shoppinghistoryservice_proto_rawDesc), len(file_shoppinghistoryservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shoppinghistoryservice_proto_goTypes,
		DependencyIndexes: file_shoppinghistoryservice_proto_depIdxs,
		MessageInfos:      file_shoppinghistoryservice_proto_msgTypes,
	}.Build()
	File_shoppinghistoryservice_proto = out.File
	file_shoppinghistoryservice_proto_goTypes = nil
	file_shoppinghistoryservice_proto_depIdxs = nil
}
