// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: shoppinghistoryservice.proto

package hipstershop

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShoppingHistoryService_CreateOrder_FullMethodName     = "/shoppinghistoryservice.ShoppingHistoryService/CreateOrder"
	ShoppingHistoryService_GetOrder_FullMethodName        = "/shoppinghistoryservice.ShoppingHistoryService/GetOrder"
	ShoppingHistoryService_GetOrdersOfUser_FullMethodName = "/shoppinghistoryservice.ShoppingHistoryService/GetOrdersOfUser"
	ShoppingHistoryService_DeleteOrder_FullMethodName     = "/shoppinghistoryservice.ShoppingHistoryService/DeleteOrder"
)

// ShoppingHistoryServiceClient is the client API for ShoppingHistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShoppingHistoryServiceClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*HistoryOrder, error)
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*HistoryOrder, error)
	GetOrdersOfUser(ctx context.Context, in *GetOrdersOfUserRequest, opts ...grpc.CallOption) (*HistoryOrders, error)
	DeleteOrder(ctx context.Context, in *DeleteOrderRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type shoppingHistoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShoppingHistoryServiceClient(cc grpc.ClientConnInterface) ShoppingHistoryServiceClient {
	return &shoppingHistoryServiceClient{cc}
}

func (c *shoppingHistoryServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*HistoryOrder, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryOrder)
	err := c.cc.Invoke(ctx, ShoppingHistoryService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoppingHistoryServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*HistoryOrder, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryOrder)
	err := c.cc.Invoke(ctx, ShoppingHistoryService_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoppingHistoryServiceClient) GetOrdersOfUser(ctx context.Context, in *GetOrdersOfUserRequest, opts ...grpc.CallOption) (*HistoryOrders, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryOrders)
	err := c.cc.Invoke(ctx, ShoppingHistoryService_GetOrdersOfUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shoppingHistoryServiceClient) DeleteOrder(ctx context.Context, in *DeleteOrderRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, ShoppingHistoryService_DeleteOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShoppingHistoryServiceServer is the server API for ShoppingHistoryService service.
// All implementations must embed UnimplementedShoppingHistoryServiceServer
// for forward compatibility.
type ShoppingHistoryServiceServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*HistoryOrder, error)
	GetOrder(context.Context, *GetOrderRequest) (*HistoryOrder, error)
	GetOrdersOfUser(context.Context, *GetOrdersOfUserRequest) (*HistoryOrders, error)
	DeleteOrder(context.Context, *DeleteOrderRequest) (*EmptyResponse, error)
	mustEmbedUnimplementedShoppingHistoryServiceServer()
}

// UnimplementedShoppingHistoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShoppingHistoryServiceServer struct{}

func (UnimplementedShoppingHistoryServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*HistoryOrder, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedShoppingHistoryServiceServer) GetOrder(context.Context, *GetOrderRequest) (*HistoryOrder, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedShoppingHistoryServiceServer) GetOrdersOfUser(context.Context, *GetOrdersOfUserRequest) (*HistoryOrders, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrdersOfUser not implemented")
}
func (UnimplementedShoppingHistoryServiceServer) DeleteOrder(context.Context, *DeleteOrderRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteOrder not implemented")
}
func (UnimplementedShoppingHistoryServiceServer) mustEmbedUnimplementedShoppingHistoryServiceServer() {
}
func (UnimplementedShoppingHistoryServiceServer) testEmbeddedByValue() {}

// UnsafeShoppingHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShoppingHistoryServiceServer will
// result in compilation errors.
type UnsafeShoppingHistoryServiceServer interface {
	mustEmbedUnimplementedShoppingHistoryServiceServer()
}

func RegisterShoppingHistoryServiceServer(s grpc.ServiceRegistrar, srv ShoppingHistoryServiceServer) {
	// If the following call panics, it indicates UnimplementedShoppingHistoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShoppingHistoryService_ServiceDesc, srv)
}

func _ShoppingHistoryService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingHistoryServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoppingHistoryService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingHistoryServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoppingHistoryService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingHistoryServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoppingHistoryService_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingHistoryServiceServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoppingHistoryService_GetOrdersOfUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersOfUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingHistoryServiceServer).GetOrdersOfUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoppingHistoryService_GetOrdersOfUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingHistoryServiceServer).GetOrdersOfUser(ctx, req.(*GetOrdersOfUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShoppingHistoryService_DeleteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShoppingHistoryServiceServer).DeleteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShoppingHistoryService_DeleteOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShoppingHistoryServiceServer).DeleteOrder(ctx, req.(*DeleteOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShoppingHistoryService_ServiceDesc is the grpc.ServiceDesc for ShoppingHistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShoppingHistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shoppinghistoryservice.ShoppingHistoryService",
	HandlerType: (*ShoppingHistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _ShoppingHistoryService_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _ShoppingHistoryService_GetOrder_Handler,
		},
		{
			MethodName: "GetOrdersOfUser",
			Handler:    _ShoppingHistoryService_GetOrdersOfUser_Handler,
		},
		{
			MethodName: "DeleteOrder",
			Handler:    _ShoppingHistoryService_DeleteOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shoppinghistoryservice.proto",
}
