apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: staging
  labels:
    app: productcatalogservice
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
    environment: staging
  ports:
    - name: grpc
      protocol: TCP
      port: 3550
      targetPort: 3550
