apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice-deployment
  namespace: staging
  labels:
    app: adservice
    environment: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
      environment: staging
  template:
    metadata:
      labels:
        app: adservice
        environment: staging
    spec:
      nodeSelector:
        kubernetes.azure.com/agentpool: stgpool
      containers:
        - name: adservice
          image: uadeel421/reliance-adservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9555
          livenessProbe:
            exec:
              command: ["/usr/bin/grpc_health_probe", "-addr=:9555"]
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            exec:
              command: ["/usr/bin/grpc_health_probe", "-addr=:9555"]
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
