apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: staging
  labels:
    app: adservice
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: adservice
    environment: staging
  ports:
    - name: grpc
      protocol: TCP
      port: 9555
      targetPort: 9555
