apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-productcatalog
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ coalesce .Values.global.secretProvider.userAssignedIdentityID .Values.secretProvider.userAssignedIdentityID | quote }}
    keyvaultName: {{ coalesce .Values.global.secretProvider.keyvaultName .Values.secretProvider.keyvaultName | quote }}
    tenantId: {{ coalesce .Values.global.secretProvider.tenantId .Values.secretProvider.tenantId | quote }}
    # This section just defines WHICH secrets to get from Key Vault
    objects: |
      array:
        - |
          objectName: MYSQLUSER
          objectType: secret
        - |
          objectName: MYSQLPASSWORD
          objectType: secret
        - |
          objectName: MYSQLHOST
          objectType: secret
        - |
          objectName: MYSQLPORT
          objectType: secret
        - |
          objectName: MYSQLDATABASE
          objectType: secret

  # This section creates the K8s secret with the correct keys for your app
  secretObjects:
  - secretName: productcatalog-db-creds
    type: Opaque
    data:
    - objectName: MYSQLUSER
      key: MYSQL_USER
    - objectName: MYSQLPASSWORD
      key: MYSQL_PASSWORD
    - objectName: MYSQLHOST
      key: MYSQL_HOST
    - objectName: MYSQLPORT
      key: MYSQL_PORT
    - objectName: MYSQLDATABASE
      key: MYSQL_DATABASE
    