apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: staging
  labels:
    app: shippingservice
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: shippingservice
    environment: staging
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
