apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aegis-system

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - dashboard-auth.yaml
  - backend-rbac.yaml
  - backend.yaml
  - dashboard.yaml
  - ingress.yaml
  - otel-collector-config.yaml
  - otel-collector.yaml
  - prometheus-config.yaml
  - prometheus.yaml
  - loki-config.yaml
  - loki.yaml
  - promtail-config.yaml
  - promtail.yaml
  - grafana-datasources.yaml
  - grafana.yaml
  - jaeger.yaml
  - redis-exporter.yaml
  - kube-state-metrics.yaml
  - node-exporter.yaml
  - cadvisor.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: aegis
      app.kubernetes.io/managed-by: kustomize
