apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  loki-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    common:
      path_prefix: /loki
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
    schema_config:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    storage_config:
      filesystem:
        chunks_directory: /loki/chunks
        rules_directory: /loki/rules
    compactor:
      working_directory: /loki/compactor
    limits_config:
      ingestion_rate_mb: 8
      ingestion_burst_size_mb: 16
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    analytics:
      reporting_enabled: false
