replicaCount: 1
environment: staging

image:
  repository: uadeel421/reliance-cartservice
  pullPolicy: Always
  tag: "latest"

service:
  port: 8080

nodeSelector:
  pool: stagingpool

# This secret will be created from the values below
secrets:
  CartStore: "AzureMySQL"
  
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
