apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice-deployment
  namespace: staging
  labels:
    app: currencyservice
    environment: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
      environment: staging
  template:
    metadata:
      labels:
        app: currencyservice
        environment: staging
    spec:
      nodeSelector:
        kubernetes.azure.com/agentpool: stgpool
      containers:
        - name: currencyservice
          image: uadeel421/reliance-currencyservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
          envFrom:  
            - configMapRef:
                name: currencyservice-config
          livenessProbe:
            exec:
              command: ["/usr/bin/grpc_health_probe", "-addr=:7000"]
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            exec:
              command: ["/usr/bin/grpc_health_probe", "-addr=:7000"]
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
