apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: staging
  labels:
    app: currencyservice
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: currencyservice
    environment: staging
  ports:
    - name: grpc
      protocol: TCP
      port: 7000
      targetPort: 7000
