apiVersion: v1
kind: Secret
metadata:
  name: products-secrets
  namespace: staging
type: Opaque
data:
  MYSQL_USER: a3BhZG1pbg==
  MYSQL_PASSWORD: d2VsY29tZTc4Xg==
  # liverwdbserver.mysql.database.azure.com
  MYSQL_HOST: bGl2ZXJ3ZGJzZXJ2ZXIubXlzcWwuZGF0YWJhc2UuYXp1cmUuY29t
  MYSQL_PORT: MzMwNg==
  MYSQL_DATABASE: aGlwc3RlcnNob3A=
  SSL_CERT_PATH: L3NzbC9EaWdpQ2VydEdsb2JhbFJvb3RDQS5jcnQucGVt
