apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    environment: {{ coalesce .Values.global.environment .Values.environment | quote }}
    
data:
  # First, add all the global service endpoints
  {{- toYaml .Values.global.serviceEndpoints | nindent 2 }}

  # Then, add any service-specific configMap values
  {{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
