apiVersion: v1
kind: Service
metadata:
  name: frontend-internal-service
  namespace: staging
  labels:
    app: frontend
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: frontend
    environment: staging
  ports:
    - name: http
      protocol: TCP
      port: 8080
      # This must match the containerPort in your deployment
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external-service
  namespace: staging
  labels:
    app: frontend
    environment: staging
spec:
  type: LoadBalancer
  selector:
    app: frontend
    environment: staging
  ports:
    - name: http
      protocol: TCP
      port: 80
      # This must match the containerPort in your deployment
      targetPort: 8080
