sonar.projectKey=online-boutique-productcatalogservice
sonar.projectName=Online Boutique - Product Catalog Service

sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.exclusions=**/*_test.go,genproto/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out