replicaCount: 1
environment: staging

image:
  repository: uadeel421/reliance-recommendationservice
  pullPolicy: Always
  tag: "latest"

service:
  port: 8080

nodeSelector:
  workload-type: staging-pool

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
