apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-product-frontend
  labels:
    app: react-product-frontend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-product-frontend
  template:
    metadata:
      labels:
        app: react-product-frontend
        version: v1
    spec:
      serviceAccountName: react-product-frontend
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      containers:
      - name: frontend
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: react-product-frontend:latest
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: logs-volume
          mountPath: /app/logs
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: logs-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: react-product-frontend
  labels:
    app: react-product-frontend
spec:
  type: LoadBalancer
  selector:
    app: react-product-frontend
  ports:
  - name: http
    port: 80
    targetPort: 3001
    protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: react-product-frontend
  labels:
    app: react-product-frontend
