apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- metrics-server.yaml
- hpa-frontend.yaml
- hpa-cartservice.yaml
- hpa-checkoutservice.yaml
- hpa-productcatalogservice.yaml
- hpa-recommendationservice.yaml
- hpa-currencyservice.yaml
