//
// Autogenerated by Thrift Compiler (0.16.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');


var ttypes = require('./demo_types');
//HELPER FUNCTIONS AND STRUCTURES

var CheckoutService_PlaceOrder_args = function(args) {
  this.user_id = null;
  this.user_currency = null;
  this.address = null;
  this.email = null;
  this.credit_card = null;
  if (args) {
    if (args.user_id !== undefined && args.user_id !== null) {
      this.user_id = args.user_id;
    }
    if (args.user_currency !== undefined && args.user_currency !== null) {
      this.user_currency = args.user_currency;
    }
    if (args.address !== undefined && args.address !== null) {
      this.address = new ttypes.Address(args.address);
    }
    if (args.email !== undefined && args.email !== null) {
      this.email = args.email;
    }
    if (args.credit_card !== undefined && args.credit_card !== null) {
      this.credit_card = new ttypes.CreditCardInfo(args.credit_card);
    }
  }
};
CheckoutService_PlaceOrder_args.prototype = {};
CheckoutService_PlaceOrder_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.user_id = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.user_currency = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRUCT) {
        this.address = new ttypes.Address();
        this.address.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.email = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRUCT) {
        this.credit_card = new ttypes.CreditCardInfo();
        this.credit_card.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CheckoutService_PlaceOrder_args.prototype.write = function(output) {
  output.writeStructBegin('CheckoutService_PlaceOrder_args');
  if (this.user_id !== null && this.user_id !== undefined) {
    output.writeFieldBegin('user_id', Thrift.Type.STRING, 1);
    output.writeString(this.user_id);
    output.writeFieldEnd();
  }
  if (this.user_currency !== null && this.user_currency !== undefined) {
    output.writeFieldBegin('user_currency', Thrift.Type.STRING, 2);
    output.writeString(this.user_currency);
    output.writeFieldEnd();
  }
  if (this.address !== null && this.address !== undefined) {
    output.writeFieldBegin('address', Thrift.Type.STRUCT, 3);
    this.address.write(output);
    output.writeFieldEnd();
  }
  if (this.email !== null && this.email !== undefined) {
    output.writeFieldBegin('email', Thrift.Type.STRING, 4);
    output.writeString(this.email);
    output.writeFieldEnd();
  }
  if (this.credit_card !== null && this.credit_card !== undefined) {
    output.writeFieldBegin('credit_card', Thrift.Type.STRUCT, 5);
    this.credit_card.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CheckoutService_PlaceOrder_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.OrderResult(args.success);
    }
  }
};
CheckoutService_PlaceOrder_result.prototype = {};
CheckoutService_PlaceOrder_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.OrderResult();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CheckoutService_PlaceOrder_result.prototype.write = function(output) {
  output.writeStructBegin('CheckoutService_PlaceOrder_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CheckoutServiceClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
CheckoutServiceClient.prototype = {};
CheckoutServiceClient.prototype.seqid = function() { return this._seqid; };
CheckoutServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };

CheckoutServiceClient.prototype.PlaceOrder = function(user_id, user_currency, address, email, credit_card, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_PlaceOrder(user_id, user_currency, address, email, credit_card);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_PlaceOrder(user_id, user_currency, address, email, credit_card);
  }
};

CheckoutServiceClient.prototype.send_PlaceOrder = function(user_id, user_currency, address, email, credit_card) {
  var output = new this.pClass(this.output);
  var params = {
    user_id: user_id,
    user_currency: user_currency,
    address: address,
    email: email,
    credit_card: credit_card
  };
  var args = new CheckoutService_PlaceOrder_args(params);
  try {
    output.writeMessageBegin('PlaceOrder', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

CheckoutServiceClient.prototype.recv_PlaceOrder = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new CheckoutService_PlaceOrder_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('PlaceOrder failed: unknown result');
};
var CheckoutServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
CheckoutServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
};
CheckoutServiceProcessor.prototype.process_PlaceOrder = function(seqid, input, output) {
  var args = new CheckoutService_PlaceOrder_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.PlaceOrder.length === 5) {
    Q.fcall(this._handler.PlaceOrder.bind(this._handler),
      args.user_id,
      args.user_currency,
      args.address,
      args.email,
      args.credit_card
    ).then(function(result) {
      var result_obj = new CheckoutService_PlaceOrder_result({success: result});
      output.writeMessageBegin("PlaceOrder", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("PlaceOrder", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.PlaceOrder(args.user_id, args.user_currency, args.address, args.email, args.credit_card, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new CheckoutService_PlaceOrder_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("PlaceOrder", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("PlaceOrder", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
