// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ratingService.proto

package cse.project.grpc;

public interface ApiResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApiResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();
}
