// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ratingService.proto

package cse.project.grpc;

public interface ShopRatingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ShopRatingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double rating = 1;</code>
   */
  double getRating();

  /**
   * <code>int64 ratingCount = 2;</code>
   */
  long getRatingCount();

  /**
   * <code>string responseMessage = 3;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 3;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();
}
