// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ratingService.proto

package cse.project.grpc;

public interface ShopRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ShopRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 rating = 1;</code>
   */
  long getRating();
}
