apiVersion: apps/v1
kind: Deployment
metadata:
  name: languageservice
  labels:
    app: languageservice
spec:
  selector:
    matchLabels:
      app: languageservice
  template:
    metadata:
      labels:
        app: languageservice
    spec:
      serviceAccountName: languageservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          ports:
            - name: express
              containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: SERVICE_NAME
              value: languageservice
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: languageservice
  labels:
    app: languageservice
spec:
  type: ClusterIP
  selector:
    app: languageservice
  ports:
<<<<<<< HEAD
    - name: grpc
=======
    - name: express
>>>>>>> aa315d45d737d85a3db388ba2aa4a14ad96c370f
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: languageservice
