resources:
  - release/kubernetes-manifests.yaml
  - httproute.yaml
images:
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend
    newName: host.docker.internal:5000/microservices-demo/frontend
    newTag: 3ac8c79
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice
    newName: host.docker.internal:5000/microservices-demo/paymentservice
    digest: sha256:1ecd55ce424ff123f96e49504e0cf23e04ed0bcd47cb5f7cfe029de083e35d78
patches:
  - path: delete-frontend-external.yaml
