resources:
  - release/kubernetes-manifests.yaml
  - httproute.yaml
images:
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend
    newName: host.docker.internal:5000/microservices-demo/frontend
    newTag: 3ac8c79
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice
    newName: host.docker.internal:5443/microservices-demo/paymentservice
    digest: sha256:564b5c023dc5a719f1dae2f67775cb0277a4b4f13ce8e490e08a42ef3db5b305
patches:
  - path: delete-frontend-external.yaml
