resources:
  - release/kubernetes-manifests.yaml
  - httproute.yaml
images:
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend
    newName: host.docker.internal:5000/microservices-demo/frontend
    newTag: 3ac8c79
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice
    newName: host.docker.internal:5000/microservices-demo/paymentservice
    digest: sha256:f4f931952ed4fa072a2356da1d15c2b9a107fc3770f4c9abf5c8851499cbbad0
patches:
  - path: delete-frontend-external.yaml
