apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice-deployment
  namespace: staging
  labels:
    app: recommendationservice
    environment: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
      environment: staging
  template:
    metadata:
      labels:
        app: recommendationservice
        environment: staging
    spec:
      nodeSelector:
        kubernetes.azure.com/agentpool: stgpool
      containers:
        - name: recommendationservice
          image: uadeel421/reliance-recommendationservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            exec:
              command: ["/usr/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            exec:
              command: ["/usr/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
s