name: Container Image CI/CD

on:
  push:
    branches: 
        - main
  pull_request:
    branches:
        - main

jobs:

  discover_services:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Discover services for build
      id: discover_services
      run: |
        SERVICES=$(find microservices-demo/src -mindepth 1 -maxdepth 1 -type d -exec test -f "{}/Dockerfile" \; -print | xargs -n1 basename)
        SERVICES_JSON=$(echo "$SERVICES" | jq -R . | jq -sc .)
        echo "Discovered services: $SERVICES_JSON"
        echo "services=$SERVICES_JSON" >> "$GITHUB_OUTPUT"
  
  build:
    needs: discover_services
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4 
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Build images
      uses: docker/build-push-action@v5
      with:
        context: ./src/${{ matrix.service }}
        file: ./src/${{ matrix.service }}/Dockerfile
        platforms: linux/amd64
        push: false
        tags: ${{ env.ECR_REGISTRY }}/${{ matrix.service }}:${{ github.sha }}

    