name: Container Image CI/CD

on:
  push:
    branches: 
        - main
  pull_request:
    branches:
        - main

jobs:

  discover_services:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Discover services for build
      id: discover_services
      run: |
        SERVICES=$(find microservices-demo/src -mindepth 1 -maxdepth 1 -type d -exec test -f "{}/Dockerfile" \; -print | xargs -n1 basename)
        SERVICES_JSON=$(echo "$SERVICES" | jq -R . | jq -sc .)
        echo "Discovered services: $SERVICES_JSON"
        echo "services=$SERVICES_JSON" >> "$GITHUB_OUTPUT"
