name: CI/CD Monorepo

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

env:
  GHCR_REPO: ghcr.io/phrafa/microservices-demo

jobs:
  build-and-push-images:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - adservice
          - cartservice
          - checkoutservice
          - currencyservice
          - emailservice
          - paymentservice
          - productcatalogservice
          - recommendationservice
          - shippingservice
          - frontend
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List directory contents
        run: ls -R

      - name: Setup Java
        if: matrix.service != 'frontend' && contains(matrix.service, 'service')
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Node.js
        if: matrix.service == 'frontend'
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build & Test
        run: |
          if [ -d "src/${{ matrix.service }}" ]; then
            cd "src/${{ matrix.service }}"
            if [ -f build.gradle ] || [ -f pom.xml ]; then
              if [ -f build.gradle ]; then
                ./gradlew clean build
              else
                mvn clean verify -DskipTests=false
              fi
            fi
            if [ -f package.json ]; then
              npm ci
              npm test -- --watch=false --browsers=ChromeHeadless
            fi
            cd -
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          if [ -d "src/${{ matrix.service }}" ]; then
            cd "src/${{ matrix.service }}"
            docker build -t ${{ env.GHCR_REPO }}-${{ matrix.service }}:latest .
            docker push ${{ env.GHCR_REPO }}-${{ matrix.service }}:latest
            cd -
          fi