name: CI/CD Monorepo

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

env:
  GHCR_REPO: ghcr.io/phrafa/microservices-demo

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - adservice
          - cartservice
          - checkoutservice
          - currencyservice
          - emailservice
          - paymentservice
          - productcatalogservice
          - recommendationservice
          - shippingservice
          - frontend
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - run: ls -R

      - name: Setup Java
        if: matrix.service == 'adservice'
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '19'

      - name: Setup .NET
        if: matrix.service == 'cartservice'
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Setup Go
        if: matrix.service == 'checkoutservice' || matrix.service == 'frontend' || matrix.service == 'productcatalogservice' || matrix.service == 'shippingservice'
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Setup Node.js
        if: matrix.service == 'currencyservice' || matrix.service == 'paymentservice'
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup Python
        if: matrix.service == 'emailservice' || matrix.service == 'recommendationservice'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build & Test
        run: |
          if [ -d "src/${{ matrix.service }}" ]; then
            cd "src/${{ matrix.service }}"
            if [ "${{ matrix.service }}" = "adservice" ]; then
              chmod +x gradlew
              ./gradlew clean build
            elif [ "${{ matrix.service }}" = "cartservice" ]; then
              dotnet test
            elif [ "${{ matrix.service }}" = "checkoutservice" ] || [ "${{ matrix.service }}" = "frontend" ] || [ "${{ matrix.service }}" = "productcatalogservice" ] || [ "${{ matrix.service }}" = "shippingservice" ]; then
              go test ./...
            elif [ "${{ matrix.service }}" = "currencyservice" ] || [ "${{ matrix.service }}" = "paymentservice" ]; then
              npm ci
            elif [ "${{ matrix.service }}" = "emailservice" ] || [ "${{ matrix.service }}" = "recommendationservice" ]; then
              pip install -r requirements.txt
            fi
            cd -
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          if [ -d "src/${{ matrix.service }}" ]; then
            if [ "${{ matrix.service }}" = "cartservice" ]; then
              cd "src/${{ matrix.service }}/src"
            else
              cd "src/${{ matrix.service }}"
            fi
            docker build -t ${{ env.GHCR_REPO }}-${{ matrix.service }}:latest .
            docker push ${{ env.GHCR_REPO }}-${{ matrix.service }}:latest
            cd -
          fi