# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Continuous Integration - Pull Request"
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'LICENSE'
      - 'kustomize/**'
      - '.github/workflows/kustomize-build-ci.yaml'
      - 'terraform/**'
      - '.github/workflows/terraform-validate-ci.yaml'
      - 'helm-chart/**'
      - '.github/workflows/helm-chart-ci.yaml'

# Ensure this workflow only runs for the most recent commit of a pull-request
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  code-tests:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-dotnet@v6
      env:
        DOTNET_INSTALL_DIR: "./.dotnet"
      with:
        dotnet-version: '10.0'
    - uses: actions/setup-go@v7
      with:
        go-version: '1.26'
    - name: Go Unit Tests
      timeout-minutes: 10
      run: |
        for GO_PACKAGE in "shippingservice" "productcatalogservice" "frontend/validator"; do
          echo "Testing $GO_PACKAGE..."
          pushd src/$GO_PACKAGE
          go test
          popd
        done
    - name: C# Unit Tests
      timeout-minutes: 10
      run: |
        dotnet test src/cartservice/
    - name: Save PR Number
      run: |
        mkdir -p .pr
        echo "${{ github.event.pull_request.number }}" > .pr/PR_NUMBER
    - name: Upload PR Number Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pr_number
        path: .pr/PR_NUMBER
