name: Deploy
run-name: Deploy to ${{ inputs.namespace }} environment

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'Kubernetes namespace to deploy to'
        required: true
        default: 'default'
        type: string

permissions:
  contents: read
  id-token: write
  
jobs:
  terraform-validate-ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_AUTENITIFICATION_KEY}}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - uses: hashicorp/setup-terraform@v3

      - name: terraform init
        working-directory: terraform
        run: terraform init

      - name: terraform validate
        working-directory: terraform
        run: terraform validate

      - name: terraform plan
        working-directory: terraform
        run: terraform plan -out=tfplan -var="namespace=${{ inputs.namespace }}"

      - name: terraform apply
        working-directory: terraform
        run: terraform apply -auto-approve tfplan