name: Build and Push Frontend

# This tells GitHub to only run this pipeline when code inside the frontend folder changes.
on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/frontend/**'

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: 643537035878
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag, and Push Image
      env:
        ECR_REGISTRY: YOUR_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com
        ECR_REPOSITORY: custom-frontend
        IMAGE_TAG: ${{ github.sha }} # This uses the unique Git commit ID as the version tag!
      run: |
        cd src/frontend
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Update Kubernetes Manifest
      env:
        ECR_REGISTRY: YOUR_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com
        ECR_REPOSITORY: custom-frontend
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Use sed to find the old image path and replace it with the brand new one
        sed -i "s|image: .*custom-frontend:.*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" kubernetes-manifests/frontend.yaml
        
        # Commit the updated YAML file back to the repository so ArgoCD sees it
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add kubernetes-manifests/frontend.yaml
        git commit -m "chore: update frontend image tag to $IMAGE_TAG [skip ci]"
        git push