name: Container Image CI

on:
  pull_request:
    branches: [main]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by GitHub Actions
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  discover_services:
    runs-on: ubuntu-latest

    outputs:
      services: ${{ steps.discover_services.outputs.services }}

    steps:
      - uses: actions/checkout@v4
      - name: Discover services
        id: discover_services
        run: |
          SERVICES=$(find microservices-demo/src -mindepth 1 -maxdepth 1 -type d -exec test -f "{}/Dockerfile" \; -print | xargs -n1 basename)
          SERVICES_JSON=$(echo "$SERVICES" | jq -R . | jq -sc .)
          
          echo "=================================="
          echo "Detected services: $SERVICES_JSON"
          echo "=================================="

          echo "services=$SERVICES_JSON" >> "$GITHUB_OUTPUT"

  build_and_scan:
    needs: discover_services
    runs-on: ubuntu-latest
    
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      pull-requests: write # for creating pull requests with scan results

    strategy:
      matrix:
        service: ${{ fromJson(needs.discover_services.outputs.services) }}

    env:
      IMAGE_TAG: ${{ matrix.service }}:ci-${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: ./microservices-demo/src/${{ matrix.service }}
          file: ./microservices-demo/src/${{ matrix.service }}/Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          tags: |
            ${{ env.IMAGE_TAG }}

      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves
          image: local://${{ env.IMAGE_TAG }}
          sarif-file: sarif.output.json
          summary: true

      - name: Upload Docker Scout SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif.output.json

      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ env.IMAGE_TAG }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif